### ISSUE TITLE
Question about noise value ranges

### ISSUE THREAD

**Issue by RemiRigal** [Scrawk/Procedural-Noise#2]
Hi @Scrawk, thank you for this amazing library!

Do you know the ranges of the returned values for each noises ? I noticed that most of them can yield values below 0 and I would like to normalize them between 0 and 1 (not just on an array as done in the example script).

Thanks.

**Comment by Scrawk** [comment]
Its hard to give a definite number. They are either around 0 to 1 or -1 to 1 but can vary a lot depending on the number of octaves. Can go up to 1.2 to for Perlin sometimes.

I find scaling the noise by 0.4 and adding 0.5 gets it with in 0 to 1 most of the time.

**Comment by RemiRigal** [comment]
I will try that thank you !
